version: '3.9'
services:
  spring-app:
    build: ./
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    networks:
        - ecommerce-net
    restart:
      always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql:8.0.42
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: docker
      MYSQL_PASSWORD: 12345678
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p12345678" ]
      interval: 5s
      timeout: 5s
      retries: 4
    command:
      - mysqld -default_authentication-plugin=mysql_native_password
    networks:
        - ecommerce-net
    restart:
      always

networks:
  ecommerce-net:
    driver: bridge